// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqpotcvijgfybbdyqkny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxcG90Y3ZpamdmeWJiZHlxa255Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MjQ5MzksImV4cCI6MjA2MDAwMDkzOX0.0PsTjERPG-8t-HKJ1Q_OpJsBuRke8obhvogHoQXIELw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);